apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scout-off-backend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scout-off-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
