#!/usr/bin/env bash
# Build, deploy, and initialize all five ScoutOff Soroban contracts on a local
# network (#1117). Writes scripts/soroban-sandbox/.env.contracts for the E2E suite.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_DIR="$(cd "$(dirname "$0")" && pwd)"
NETWORK="${SOROBAN_NETWORK:-local}"
RPC_URL="${SOROBAN_RPC_URL:-http://localhost:8000/soroban/rpc}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Standalone Network ; February 2017}"
FRIENDBOT_URL="${FRIENDBOT_URL:-http://localhost:8000/friendbot}"

export STELLAR_NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE"
export STELLAR_RPC_URL="$RPC_URL"

cd "$ROOT/contracts"

echo "[deploy] building WASM crates…"
cargo build --release --target wasm32-unknown-unknown

# Fund (or reuse) a platform identity.
IDENTITY="${SOROBAN_IDENTITY:-sandbox-admin}"
if ! stellar keys ls 2>/dev/null | grep -qx "$IDENTITY"; then
  stellar keys generate --no-fund "$IDENTITY" || stellar keys generate "$IDENTITY"
fi
ADMIN_SECRET="$(stellar keys show "$IDENTITY")"
ADMIN_PUB="$(stellar keys address "$IDENTITY")"

echo "[deploy] funding ${ADMIN_PUB} via friendbot…"
curl -sf "${FRIENDBOT_URL}?addr=${ADMIN_PUB}" >/dev/null || true
sleep 2

deploy_one() {
  local name="$1"
  local wasm="$2"
  echo "[deploy] deploying ${name}…" >&2
  stellar contract deploy \
    --wasm "$wasm" \
    --source "$IDENTITY" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE"
}

TARGET_DIR="$ROOT/contracts/target/wasm32-unknown-unknown/release"
REGISTER_ID="$(deploy_one register "$TARGET_DIR/register.wasm")"
PROGRESS_ID="$(deploy_one progress "$TARGET_DIR/progress.wasm")"
SUBSCRIPTION_ID="$(deploy_one subscription "$TARGET_DIR/subscription.wasm")"
CONNECTION_ID="$(deploy_one connection "$TARGET_DIR/connection.wasm")"
PLAYER_TOKEN_ID="$(deploy_one player_token "$TARGET_DIR/player_token.wasm" || true)"

echo "[deploy] initializing contracts…"

# initialize signatures vary by crate — invoke best-effort with admin.
invoke_init() {
  local cid="$1"
  shift
  stellar contract invoke \
    --id "$cid" \
    --source "$IDENTITY" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    -- "$@" || echo "[deploy] warn: init invoke failed for $cid ($*)" >&2
}

invoke_init "$REGISTER_ID" initialize --admin "$ADMIN_PUB"
invoke_init "$PROGRESS_ID" initialize --admin "$ADMIN_PUB" --register_contract "$REGISTER_ID"
invoke_init "$SUBSCRIPTION_ID" initialize --admin "$ADMIN_PUB"
invoke_init "$CONNECTION_ID" initialize --admin "$ADMIN_PUB" --register_contract "$REGISTER_ID"

# Wire progress + connection as authorized updaters on register when the
# entrypoint exists.
invoke_init "$REGISTER_ID" add_authorized_updater --updater "$PROGRESS_ID"
invoke_init "$REGISTER_ID" add_authorized_updater --updater "$CONNECTION_ID"

ENV_FILE="$OUT_DIR/.env.contracts"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/soroban-sandbox/deploy.sh — do not commit secrets to git.
NETWORK=standalone
NETWORK_PASSPHRASE=${NETWORK_PASSPHRASE}
SOROBAN_RPC_URL=${RPC_URL}
HORIZON_URL=${HORIZON_URL:-http://localhost:8000}
PLATFORM_SECRET_KEY=${ADMIN_SECRET}
ADMIN_WALLET=${ADMIN_PUB}
REGISTER_CONTRACT_ID=${REGISTER_ID}
PROGRESS_CONTRACT_ID=${PROGRESS_ID}
SUBSCRIPTION_CONTRACT_ID=${SUBSCRIPTION_ID}
CONNECTION_CONTRACT_ID=${CONNECTION_ID}
PLAYER_TOKEN_CONTRACT_ID=${PLAYER_TOKEN_ID:-}
CONTRACT_ID=${REGISTER_ID}
EOF

echo "[deploy] wrote ${ENV_FILE}"
echo "[deploy] REGISTER=${REGISTER_ID}"
echo "[deploy] PROGRESS=${PROGRESS_ID}"
echo "[deploy] SUBSCRIPTION=${SUBSCRIPTION_ID}"
echo "[deploy] CONNECTION=${CONNECTION_ID}"
