import { Keypair } from "@stellar/stellar-sdk";
import { STELLAR_ADDRESS_RE, isValidIpAddress } from "../../src/utils/validators";

describe("STELLAR_ADDRESS_RE", () => {
  describe("valid Stellar addresses", () => {
    it("matches a valid Stellar public key generated by SDK", () => {
      const keypair = Keypair.random();
      const validAddress = keypair.publicKey();
      expect(STELLAR_ADDRESS_RE.test(validAddress)).toBe(true);
    });

    it("matches multiple valid Stellar public keys", () => {
      for (let i = 0; i < 5; i++) {
        const keypair = Keypair.random();
        const validAddress = keypair.publicKey();
        expect(STELLAR_ADDRESS_RE.test(validAddress)).toBe(true);
        expect(validAddress.length).toBe(56);
        expect(validAddress[0]).toBe("G");
      }
    });

    it("matches Stellar addresses with all uppercase letters", () => {
      const validAddress =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(validAddress)).toBe(true);
      expect(validAddress.length).toBe(56);
    });

    it("matches Stellar addresses using digits 2-7 (base32 set)", () => {
      const validAddress =
        "G2222222222222222222222222222222222222222222222222222222";
      expect(STELLAR_ADDRESS_RE.test(validAddress)).toBe(true);
    });

    it("matches Stellar address with mixed uppercase and base32 digits", () => {
      const validAddress =
        "GABCDEFGHIJKLMNOPQRSTUVWXYZ2345672345672345672345672345A";
      expect(STELLAR_ADDRESS_RE.test(validAddress)).toBe(true);
      expect(validAddress.length).toBe(56);
    });

    it("accepts any correctly formatted 56-character address starting with G", () => {
      const validAddress =
        "GCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB";
      expect(STELLAR_ADDRESS_RE.test(validAddress)).toBe(true);
      expect(validAddress.length).toBe(56);
    });
  });

  describe("invalid Stellar addresses - wrong starting character", () => {
    it("rejects addresses starting with S (secret key)", () => {
      const secretKey =
        "SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(secretKey)).toBe(false);
    });

    it("rejects addresses starting with lowercase g", () => {
      const invalidAddress =
        "gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(invalidAddress)).toBe(false);
    });

    it("rejects addresses starting with a number", () => {
      const invalidAddress =
        "0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(invalidAddress)).toBe(false);
    });

    it("rejects addresses starting with other letters", () => {
      const invalidAddress =
        "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(invalidAddress)).toBe(false);
    });

    it("rejects addresses starting with C", () => {
      const invalidAddress =
        "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(invalidAddress)).toBe(false);
    });

    it("rejects addresses starting with X", () => {
      const invalidAddress =
        "XAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(invalidAddress)).toBe(false);
    });
  });

  describe("invalid Stellar addresses - wrong length", () => {
    it("rejects addresses that are too short", () => {
      const tooShort =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(tooShort)).toBe(false);
      expect(tooShort.length).toBe(55); // 1 character short
    });

    it("rejects addresses that are too long", () => {
      // 57 characters: G + 56 A's
      const tooLong = "G" + "A".repeat(56);
      expect(STELLAR_ADDRESS_RE.test(tooLong)).toBe(false);
      expect(tooLong.length).toBe(57); // 1 character too long
    });

    it("rejects very short input", () => {
      const veryShort = "GABC";
      expect(STELLAR_ADDRESS_RE.test(veryShort)).toBe(false);
    });

    it("rejects single character", () => {
      expect(STELLAR_ADDRESS_RE.test("G")).toBe(false);
    });

    it("rejects empty string", () => {
      expect(STELLAR_ADDRESS_RE.test("")).toBe(false);
    });
  });

  describe("invalid Stellar addresses - invalid characters", () => {
    it("rejects addresses with lowercase letters", () => {
      const withLowercase =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa";
      expect(STELLAR_ADDRESS_RE.test(withLowercase)).toBe(false);
    });

    it("rejects addresses with invalid digit 0", () => {
      const withInvalidDigit =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AA";
      expect(STELLAR_ADDRESS_RE.test(withInvalidDigit)).toBe(false);
    });

    it("rejects addresses with invalid digit 1", () => {
      const withInvalidDigit =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1AA";
      expect(STELLAR_ADDRESS_RE.test(withInvalidDigit)).toBe(false);
    });

    it("rejects addresses with digit 8", () => {
      const withInvalidDigit =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AA";
      expect(STELLAR_ADDRESS_RE.test(withInvalidDigit)).toBe(false);
    });

    it("rejects addresses with digit 9", () => {
      const withInvalidDigit =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9AA";
      expect(STELLAR_ADDRESS_RE.test(withInvalidDigit)).toBe(false);
    });

    it("rejects addresses with special characters", () => {
      const withSpecialChar =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!AAAA";
      expect(STELLAR_ADDRESS_RE.test(withSpecialChar)).toBe(false);
    });

    it("rejects addresses with hyphens", () => {
      const withHyphen =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-AAAA";
      expect(STELLAR_ADDRESS_RE.test(withHyphen)).toBe(false);
    });

    it("rejects addresses with spaces", () => {
      const withSpace =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAA";
      expect(STELLAR_ADDRESS_RE.test(withSpace)).toBe(false);
    });

    it("rejects addresses with underscores", () => {
      const withUnderscore =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_AAAA";
      expect(STELLAR_ADDRESS_RE.test(withUnderscore)).toBe(false);
    });

    it("rejects addresses with dots", () => {
      const withDot =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.AAAA";
      expect(STELLAR_ADDRESS_RE.test(withDot)).toBe(false);
    });
  });

  describe("edge cases", () => {
    it("does not match null", () => {
      expect(STELLAR_ADDRESS_RE.test(null as unknown as string)).toBe(false);
    });

    it("does not match undefined", () => {
      expect(STELLAR_ADDRESS_RE.test(undefined as unknown as string)).toBe(
        false,
      );
    });

    it("does not match a Stellar address with leading whitespace", () => {
      const withWhitespace =
        " GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(withWhitespace)).toBe(false);
    });

    it("does not match a Stellar address with trailing whitespace", () => {
      const withTrailingSpace =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ";
      expect(STELLAR_ADDRESS_RE.test(withTrailingSpace)).toBe(false);
    });

    it("does not match when address is embedded in another string", () => {
      const embedded =
        "XGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(embedded)).toBe(false);
    });

    it("does not match when address is a suffix of another string", () => {
      const suffix = "PREFIXGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(suffix)).toBe(false);
    });

    it("handles very long input gracefully", () => {
      const veryLong = "G" + "A".repeat(10000);
      expect(STELLAR_ADDRESS_RE.test(veryLong)).toBe(false);
    });

    it("does not match when address appears in the middle of text", () => {
      const middle =
        "prefix GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA suffix";
      expect(STELLAR_ADDRESS_RE.test(middle)).toBe(false);
    });
  });

  describe("base32 character set validation (A-Z, 2-7)", () => {
    it("accepts all uppercase letters (A-Z)", () => {
      const allLetters = "G" + "Z".repeat(55);
      expect(STELLAR_ADDRESS_RE.test(allLetters)).toBe(true);
      expect(allLetters.length).toBe(56);
    });

    it("accepts all valid base32 digits (2-7)", () => {
      const allDigits2 =
        "G2222222222222222222222222222222222222222222222222222222";
      expect(STELLAR_ADDRESS_RE.test(allDigits2)).toBe(true);

      const allDigits7 =
        "G7777777777777777777777777777777777777777777777777777777";
      expect(STELLAR_ADDRESS_RE.test(allDigits7)).toBe(true);
    });

    it("rejects 0 as it is not in base32 character set", () => {
      const with0 = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAA";
      expect(STELLAR_ADDRESS_RE.test(with0)).toBe(false);
    });

    it("rejects 1 as it is not in base32 character set", () => {
      const with1 = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1AAA";
      expect(STELLAR_ADDRESS_RE.test(with1)).toBe(false);
    });

    it("rejects 8 as it is outside base32 range", () => {
      const with8 = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAA";
      expect(STELLAR_ADDRESS_RE.test(with8)).toBe(false);
    });

    it("rejects 9 as it is outside base32 range", () => {
      const with9 = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9AAA";
      expect(STELLAR_ADDRESS_RE.test(with9)).toBe(false);
    });

    it("accepts mixed valid letters and digits", () => {
      const mixed =
        "G" + "A2B3C4D5E6F7G2H3I4J5K6L7M2N3O4P5Q6R7S2T3U4V5W6X7Y2Z3A4B";
      expect(STELLAR_ADDRESS_RE.test(mixed)).toBe(true);
      expect(mixed.length).toBe(56);
    });
  });

  describe("regex anchoring (^ and $)", () => {
    it("requires address to start at beginning of string (no prefix)", () => {
      const prefix = "PREFIXGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(prefix)).toBe(false);
    });

    it("requires address to end at end of string (no suffix)", () => {
      const suffix =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASUFFIX";
      expect(STELLAR_ADDRESS_RE.test(suffix)).toBe(false);
    });

    it("accepts address when it is the complete string", () => {
      const justAddress =
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
      expect(STELLAR_ADDRESS_RE.test(justAddress)).toBe(true);
    });

    it("does not match when address appears in the middle of text", () => {
      const middle =
        "prefix GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA suffix";
      expect(STELLAR_ADDRESS_RE.test(middle)).toBe(false);
    });
  });

  describe("real-world Stellar address examples from SDK", () => {
    it("matches SDK-generated addresses consistently", () => {
      const addresses: string[] = [];
      for (let i = 0; i < 10; i++) {
        const keypair = Keypair.random();
        addresses.push(keypair.publicKey());
      }

      addresses.forEach((addr) => {
        expect(STELLAR_ADDRESS_RE.test(addr)).toBe(true);
        expect(addr.length).toBe(56);
        expect(addr[0]).toBe("G");
      });
    });

    it("correctly identifies that generated addresses match the pattern", () => {
      const keypair = Keypair.random();
      const publicKey = keypair.publicKey();

      // Test the address is valid
      expect(STELLAR_ADDRESS_RE.test(publicKey)).toBe(true);

      // Test that modifying it breaks validation
      expect(STELLAR_ADDRESS_RE.test(publicKey.substring(0, 55))).toBe(false);
      expect(STELLAR_ADDRESS_RE.test("S" + publicKey.substring(1))).toBe(false);
    });
  });
});

describe("isValidIpAddress", () => {
  it("accepts valid IPv4 addresses", () => {
    expect(isValidIpAddress("203.0.113.5")).toBe(true);
    expect(isValidIpAddress("0.0.0.0")).toBe(true);
    expect(isValidIpAddress("255.255.255.255")).toBe(true);
  });

  it("accepts valid IPv6 addresses", () => {
    expect(isValidIpAddress("::1")).toBe(true);
    expect(isValidIpAddress("2001:db8::1")).toBe(true);
    expect(isValidIpAddress("fe80::1ff:fe23:4567:890a")).toBe(true);
  });

  it("rejects an empty string", () => {
    expect(isValidIpAddress("")).toBe(false);
  });

  it("rejects a malformed dotted-quad address", () => {
    expect(isValidIpAddress("999.999.999.999")).toBe(false);
  });

  it("rejects random text", () => {
    expect(isValidIpAddress("not-an-ip")).toBe(false);
  });

  it("rejects an IPv4 address with a trailing port", () => {
    expect(isValidIpAddress("203.0.113.5:8080")).toBe(false);
  });

  it("rejects non-string input", () => {
    expect(isValidIpAddress(null as unknown as string)).toBe(false);
    expect(isValidIpAddress(undefined as unknown as string)).toBe(false);
  });
});
